### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by bastianhjaeger** [angular-university/service-workers-guide#2]
While I like the way the "Practical Tour" is written on https://blog.angular-university.io/service-workers/ I do not see any instructions on how to run the code form this repository.

I would assume `ng ...` , but I would love to see a peace of documentation on that "practical" part.

**Comment by jpangburn** [comment]
You could use "npx serve".  It's just plain HTML/JS/CSS so you just need a web server to host it.  If you have a recent Node.js installed this will work.
